### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by bkolada** [donpiekarz/spellbook#1]
During installing pip/python2.7 on fedora I had following error:

```
➜   pip install spellbook          
Collecting spellbook
  Using cached spellbook-1.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w_5wVv/spellbook/setup.py", line 7, in <module>
        from spellbooker.application import VERSION
      File "/tmp/pip-build-w_5wVv/spellbook/spellbooker/application.py", line 9, in <module>
        from builtins import *
    ImportError: No module named builtins

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w_5wVv/spellbook

```

**Comment by bkolada** [comment]
Problem is because of python2 and 3 difference `builtins` were renamed in py3 from `__builtin__`. After that change everything worked.

**Comment by bkolada** [comment]
So yeah it could be problem of future but as you mentioned it's one of requirements and it should be somehow installed. 

Here is log from installation after my little change:

```
running install
running bdist_egg
running egg_info
creating spellbook.egg-info
writing requirements to spellbook.egg-info/requires.txt
writing spellbook.egg-info/PKG-INFO
writing top-level names to spellbook.egg-info/top_level.txt
writing dependency_links to spellbook.egg-info/dependency_links.txt
writing entry points to spellbook.egg-info/entry_points.txt
writing manifest file 'spellbook.egg-info/SOURCES.txt'
reading manifest file 'spellbook.egg-info/SOURCES.txt'
writing manifest file 'spellbook.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/spellbooker
copying spellbooker/application.py -> build/lib/spellbooker
copying spellbooker/__init__.py -> build/lib/spellbooker
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/spellbooker
copying build/lib/spellbooker/application.py -> build/bdist.linux-x86_64/egg/spellbooker
copying build/lib/spellbooker/__init__.py -> build/bdist.linux-x86_64/egg/spellbooker
byte-compiling build/bdist.linux-x86_64/egg/spellbooker/application.py to application.pyc
byte-compiling build/bdist.linux-x86_64/egg/spellbooker/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying spellbook.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying spellbook.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying spellbook.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying spellbook.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying spellbook.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying spellbook.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/spellbook-1.1.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing spellbook-1.1.4-py2.7.egg
Copying spellbook-1.1.4-py2.7.egg to /usr/lib/python2.7/site-packages
Adding spellbook 1.1.4 to easy-install.pth file
Installing spellbook script to /usr/bin

Installed /usr/lib/python2.7/site-packages/spellbook-1.1.4-py2.7.egg
Processing dependencies for spellbook==1.1.4
Searching for future
Reading https://pypi.python.org/simple/future/
Best match: future 0.15.2
Downloading https://pypi.python.org/packages/source/f/future/future-0.15.2.tar.gz#md5=a68eb3c90b3b76714c5ceb8c09ea3a06
Processing future-0.15.2.tar.gz
Writing /tmp/easy_install-RIUb7B/future-0.15.2/setup.cfg
Running future-0.15.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-RIUb7B/future-0.15.2/egg-dist-tmp-Fyw3Vq
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
zip_safe flag not set; analyzing archive contents...
future.standard_library.__init__: module references __file__
future.standard_library.__init__: module references __path__
future.backports.test.support: module references __file__
future.backports.test.ssl_servers: module references __file__
future.utils.__init__: module MAY be using inspect.stack
past.builtins.misc: module MAY be using inspect.stack
past.translation.__init__: module references __file__
past.translation.__init__: module references __path__
creating /usr/lib/python2.7/site-packages/future-0.15.2-py2.7.egg
Extracting future-0.15.2-py2.7.egg to /usr/lib/python2.7/site-packages
Adding future 0.15.2 to easy-install.pth file
Installing pasteurize script to /usr/bin
Installing futurize script to /usr/bin

Installed /usr/lib/python2.7/site-packages/future-0.15.2-py2.7.egg
Finished processing dependencies for spellbook==1.1.4
```

As you can see he load first spell book and after that he tried install requirements. I think it can cause  a lot of problems with beginner users. At least mention that at first you have to install future by yourself.

**Comment by donpiekarz** [comment]
Ok, I see.

The problem here is related to get version of spellbook. I will move version somewhere else.

**Comment by donpiekarz** [comment]
Version 1.1.5 should be fixed. Could you retest?

**Comment by donpiekarz** [comment]
For me it works :)
